
ouputName = 'ExampleOutputName';
RunWorldRecipes('outputName',ouputName, ...
    'imageWidth',320, ...
    'imageHeight',240, ...
    'cropImageHalfSize', 25, ... % Size of cropped image is 2*cropImageHalfSize+1
    'nOtherObjectSurfaceReflectance', 999, ... % Number of random surfaces to choose from
    'luminanceLevels',linspace(0.2,0.6,5), ... 
    'reflectanceNumbers',(1:5), ... % There are dummy indices for each recipe
    'nInsertedLights', 1, ... % No of inserted lights
    'nInsertObjects', 0, ... % These are objects other than target objects
    'otherObjectReflectanceRandom', true, ... 
    'illuminantSpectraRandom', true, ...
    'minMeanIlluminantLevel', 1, ...  % These two options are to control the
    'maxMeanIlluminantLevel', 100, ... % mean value (Brightness) of the illuminant
    'illuminantSpectrumNotFlat',true, ... % true is random shape, false flat
    'targetSpectrumNotFlat',true, ...    % true is random shape, false flat
    'targetSpectrumSameShape', false, ... % true = shame spectra for all images
    'lightPositionRandom',true, ... % The flase option will only work for library base scene
    'lightScaleRandom',true, ...
    'targetPositionRandom',true, ... % The flase option will only work for library base scene
    'targetScaleRandom',false, ...
    'shapeSet',{'Barrel', 'BigBall', 'ChampagneBottle', 'RingToy', 'SmallBall', 'Xylophone'}, ...
    'baseSceneSet',{'CheckerBoard', 'IndoorPlant', 'Library', 'Mill', 'TableChairs', 'Warehouse'}, ...    
    'mosaicHalfSize', 25, ...
    'nRandomRotations', 0);